"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Settings that differ per machine live in .env, which is not committed.
# .env.example lists every key with a safe default.
load_dotenv(BASE_DIR / ".env")


def env(key, default=None):
    """Read a setting from the environment, falling back to `default`."""
    return os.environ.get(key, default)


def env_bool(key, default=False):
    return str(env(key, str(default))).strip().lower() in {"1", "true", "yes", "on"}


def env_list(key, default=""):
    return [v.strip() for v in str(env(key, default)).split(",") if v.strip()]


# True while `manage.py test` is running, which swaps the database for an
# in-memory SQLite one so the suite needs no server and leaves no files.
RUNNING_TESTS = "test" in sys.argv or env_bool("DJANGO_TESTING")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    "django-insecure-u+(fbxu_a_zcobn_)w&+#ib&!ngsk3#e+g*dl5ci^coy04@gx0",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    # local
    "app",
]

# The audit block points at this model, so it must be the auth user model.
AUTH_USER_MODEL = "app.AppUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL in every real environment. JSONField needs MySQL 5.7+ (native JSON
# type) and CHECK constraints need 8.0.16+ — on anything older MySQL parses
# CHECK and ignores it, so the constraints in models.py would be decorative.
# MariaDB 10.2+ satisfies both.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("MYSQL_DB", "esquared_academy"),
        "USER": env("MYSQL_USER", "esquared"),
        "PASSWORD": env("MYSQL_PASSWORD", ""),
        "HOST": env("MYSQL_HOST", "127.0.0.1"),
        "PORT": env("MYSQL_PORT", "3306"),
        "CONN_MAX_AGE": int(env("MYSQL_CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": int(env("MYSQL_CONNECT_TIMEOUT", "10")),
            # STRICT_TRANS_TABLES turns silent truncation into an error.
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "TEST": {
            "CHARSET": "utf8mb4",
            "COLLATION": "utf8mb4_0900_ai_ci",
        },
    }
}

# Unit tests run against an in-memory database: created per run, held in
# RAM, discarded at the end. (Django has no H2 backend — H2 is a Java
# database — and SQLite's :memory: mode is the direct equivalent here.)
# Set DJANGO_TEST_ON_MYSQL=true to run the suite against MySQL instead,
# which is what CI should do before a release: SQLite is lenient about
# column types and ignores CHECK constraints Django cannot express.
if RUNNING_TESTS and not env_bool("DJANGO_TEST_ON_MYSQL"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
        "TEST": {"NAME": ":memory:"},
    }


# ---------------------------------------------------------------------
# REST framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "E Squared Academy API",
    "DESCRIPTION": (
        "Assessment platform for E Squared Academy.\n\n"
        "Grades are classes. Question papers are versioned and immutable once "
        "locked; a locked version pins the prompt version each text question "
        "is marked by. Nothing is deleted \u2014 rows are voided, and purging "
        "is a separate, logged operation."
    ),
    "VERSION": "2.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api",
    "ENUM_NAME_OVERRIDES": {
        "TextFormatEnum": "app.models.TextFormat.choices",
        "QuestionTypeEnum": "app.models.QuestionType.choices",
        "ToleranceTypeEnum": "app.models.ToleranceType.choices",
        "SyllabusStatusEnum": "app.models.SyllabusStatus.choices",
        "PromptStatusEnum": "app.models.PromptStatus.choices",
        "PaperPurposeEnum": "app.models.PaperPurpose.choices",
        "PaperStatusEnum": "app.models.PaperStatus.choices",
        "CohortPurposeEnum": "app.models.CohortPurpose.choices",
        "MarkingMethodEnum": "app.models.MarkingMethod.choices",
        "AttemptStateEnum": "app.models.AttemptState.choices",
        "EvalMethodEnum": "app.models.EvalMethod.choices",
    },
    "TAGS": [
        {"name": "grades", "description": "Grades, which are also the classes."},
        {"name": "students", "description": "Students and their enrolments."},
        {"name": "syllabi", "description": "A subject taught to a grade in a year."},
        {"name": "questions", "description": "The reusable question bank."},
        {"name": "paper-versions", "description": "Frozen question cohorts."},
        {"name": "attempts", "description": "Sittings, answers and marking."},
    ],
}
