"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Settings that differ per machine live in .env, which is not committed.
# .env.example lists every key with a safe default.
load_dotenv(BASE_DIR / ".env")


def env(key, default=None):
    """Read a setting from the environment, falling back to `default`."""
    return os.environ.get(key, default)


def env_bool(key, default=False):
    return str(env(key, str(default))).strip().lower() in {"1", "true", "yes", "on"}


def env_list(key, default=""):
    return [v.strip() for v in str(env(key, default)).split(",") if v.strip()]


# True while `manage.py test` is running, which swaps the database for an
# in-memory SQLite one so the suite needs no server and leaves no files.
RUNNING_TESTS = "test" in sys.argv or env_bool("DJANGO_TESTING")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    "django-insecure-u+(fbxu_a_zcobn_)w&+#ib&!ngsk3#e+g*dl5ci^coy04@gx0",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    # Django JET Reboot skins the admin. Both entries must precede
    # django.contrib.admin so their templates win.
    "jet.dashboard",
    "jet",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    # local
    "app",
]

# The audit block points at this model, so it must be the auth user model.
AUTH_USER_MODEL = "app.AppUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Publishes request.user so the audit block can stamp itself.
    # Must come after AuthenticationMiddleware.
    "app.audit.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL in every real environment. JSONField needs MySQL 5.7+ (native JSON
# type) and CHECK constraints need 8.0.16+ — on anything older MySQL parses
# CHECK and ignores it, so the constraints in models.py would be decorative.
# MariaDB 10.2+ satisfies both.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("MYSQL_DB", "esquared_academy"),
        "USER": env("MYSQL_USER", "esquared"),
        "PASSWORD": env("MYSQL_PASSWORD", ""),
        "HOST": env("MYSQL_HOST", "127.0.0.1"),
        "PORT": env("MYSQL_PORT", "3306"),
        "CONN_MAX_AGE": int(env("MYSQL_CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": int(env("MYSQL_CONNECT_TIMEOUT", "10")),
            # STRICT_TRANS_TABLES turns silent truncation into an error.
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "TEST": {
            "CHARSET": "utf8mb4",
            "COLLATION": "utf8mb4_0900_ai_ci",
        },
    }
}

# Unit tests run against an in-memory database: created per run, held in
# RAM, discarded at the end. (Django has no H2 backend — H2 is a Java
# database — and SQLite's :memory: mode is the direct equivalent here.)
# Set DJANGO_TEST_ON_MYSQL=true to run the suite against MySQL instead,
# which is what CI should do before a release: SQLite is lenient about
# column types and ignores CHECK constraints Django cannot express.
if RUNNING_TESTS and not env_bool("DJANGO_TEST_ON_MYSQL"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
        "TEST": {"NAME": ":memory:"},
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("DJANGO_TIME_ZONE", "Asia/Karachi")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

# Uploaded files. One root, a flat folder per kind underneath it —
# text/ audio/ video/ picture/ other/ — plus _incoming/ for chunks of
# uploads still in progress. See app/files.py.
MEDIA_ROOT = Path(env("MEDIA_ROOT") or (BASE_DIR / "media"))

MEDIA_URL = env("MEDIA_URL") or "/media/"

# Large uploads arrive in chunks (see UploadSession), so no single request
# needs to be big. These bound what one request may hold: anything over
# 5 MB is streamed to a temporary file rather than buffered in memory.
FILE_UPLOAD_MAX_MEMORY_SIZE = int(env("FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(env("DATA_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024)))

# What the browser-side uploader slices files into. Bigger is faster on a
# good connection; smaller resumes more cheaply on a bad one.
UPLOAD_CHUNK_SIZE = int(env("UPLOAD_CHUNK_SIZE", str(5 * 1024 * 1024)))

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------
# REST framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "app.access.RolePermission",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Esquared Academy API",
    "DESCRIPTION": (
        "Assessment platform for Esquared Academy.\n\n"
        "Grades are classes. Question papers are versioned and immutable once "
        "locked; a locked version pins the prompt version each text question "
        "is marked by. Nothing is deleted \u2014 rows are voided, and purging "
        "is a separate, logged operation."
    ),
    "VERSION": "2.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api",
    "ENUM_NAME_OVERRIDES": {
        "TextFormatEnum": "app.models.TextFormat.choices",
        "QuestionTypeEnum": "app.models.QuestionType.choices",
        "ToleranceTypeEnum": "app.models.ToleranceType.choices",
        "SyllabusStatusEnum": "app.models.SyllabusStatus.choices",
        "PromptStatusEnum": "app.models.PromptStatus.choices",
        "PaperPurposeEnum": "app.models.PaperPurpose.choices",
        "PaperStatusEnum": "app.models.PaperStatus.choices",
        "CohortPurposeEnum": "app.models.CohortPurpose.choices",
        "MarkingMethodEnum": "app.models.MarkingMethod.choices",
        "AttemptStateEnum": "app.models.AttemptState.choices",
        "EvalMethodEnum": "app.models.EvalMethod.choices",
        "FileKindEnum": "app.files.FileKind.choices",
        "AttendanceStatusEnum": "app.models.AttendanceStatus.choices",
        "UploadStateEnum": "app.models.UploadState.choices",
    },
    "TAGS": [
        {"name": "grades", "description": "Grades, which are also the classes."},
        {"name": "students", "description": "Students and their enrolments."},
        {"name": "syllabi", "description": "A subject taught to a grade in a year."},
        {"name": "questions", "description": "The reusable question bank."},
        {"name": "paper-versions", "description": "Frozen question cohorts."},
        {"name": "attempts", "description": "Sittings, answers and marking."},
    ],
}


# ---------------------------------------------------------------------
# Admin theme — Django JET Reboot
#
# The original django-jet was abandoned in 2018; this is the maintained
# fork (last release 1.3.10, September 2024), which is what supports
# Django 4 and 5. Verified against Django 5.2 here: the index, change
# lists, change forms, inlines and filters all render.
# ---------------------------------------------------------------------
# The skin everyone gets until they pick their own.
JET_DEFAULT_THEME = env("JET_THEME", "light-violet")

# Listing themes here puts a colour picker in the admin sidebar; each user's
# choice is stored against their account and overrides the default above.
# Set JET_SHOW_THEME_PICKER=false in .env to take the picker away and hold
# everyone to JET_THEME.
JET_THEMES = [
    {"theme": "default", "color": "#47bac1", "title": "Default"},
    {"theme": "green", "color": "#44b78b", "title": "Green"},
    {"theme": "light-green", "color": "#2faa60", "title": "Light green"},
    {"theme": "light-violet", "color": "#a464c4", "title": "Light violet"},
    {"theme": "light-blue", "color": "#5EADDE", "title": "Light blue"},
    {"theme": "light-gray", "color": "#222", "title": "Light gray"},
] if env_bool("JET_SHOW_THEME_PICKER", True) else []
JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True

# The order the left menu is built in, grouped the way the ERD is:
# placement, curriculum, question bank, papers, marking, retention.
JET_SIDE_MENU_ITEMS = [
    {"label": "People & placement", "items": [
        {"name": "app.grade"},
        {"name": "app.student"},
        {"name": "app.teacher"},
        {"name": "app.enrolment"},
        {"name": "app.studentcohort"},
        {"name": "app.cohortmembership"},
    ]},
    {"label": "Curriculum", "items": [
        {"name": "app.subject"},
        {"name": "app.topic"},
        {"name": "app.syllabus"},
        {"name": "app.syllabustopic"},
        {"name": "app.studentsubject"},
        {"name": "app.teachingassignment"},
    ]},
    {"label": "Question bank", "items": [
        {"name": "app.question"},
        {"name": "app.binaryconfig"},
        {"name": "app.numericconfig"},
        {"name": "app.evaluationprompt"},
        {"name": "app.promptversion"},
    ]},
    {"label": "Papers", "items": [
        {"name": "app.questionpaper"},
        {"name": "app.paperversion"},
        {"name": "app.paperitem"},
        {"name": "app.paperassignment"},
    ]},
    {"label": "Attendance", "items": [
        {"name": "app.attendancesession"},
        {"name": "app.attendancerecord"},
    ]},
    {"label": "Files", "items": [
        {"name": "app.attachment"},
        {"name": "app.attachmentlink"},
        {"name": "app.uploadsession"},
    ]},
    {"label": "Marking", "items": [
        {"name": "app.attempt"},
        {"name": "app.answer"},
        {"name": "app.evaluation"},
    ]},
    {"label": "Administration", "items": [
        {"name": "app.appuser"},
        {"name": "auth.group"},
        {"name": "app.guardianlink"},
        {"name": "app.retentionpolicy"},
        {"name": "app.purgerun"},
    ]},
]
