"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Settings that differ per machine live in .env, which is not committed.
# .env.example lists every key with a safe default.
load_dotenv(BASE_DIR / ".env")


def env(key, default=None):
    """Read a setting from the environment, falling back to `default`."""
    return os.environ.get(key, default)


def env_bool(key, default=False):
    return str(env(key, str(default))).strip().lower() in {"1", "true", "yes", "on"}


def env_list(key, default=""):
    return [v.strip() for v in str(env(key, default)).split(",") if v.strip()]


# True while `manage.py test` is running, which swaps the database for an
# in-memory SQLite one so the suite needs no server and leaves no files.
RUNNING_TESTS = "test" in sys.argv or env_bool("DJANGO_TESTING")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    "django-insecure-u+(fbxu_a_zcobn_)w&+#ib&!ngsk3#e+g*dl5ci^coy04@gx0",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    # Django JET Reboot skins the admin. Both entries must precede
    # django.contrib.admin so their templates win.
    "jet.dashboard",
    "jet",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    # local
    "app",
]

# The audit block points at this model, so it must be the auth user model.
AUTH_USER_MODEL = "app.AppUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Publishes request.user so the audit block can stamp itself.
    # Must come after AuthenticationMiddleware.
    "app.audit.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # A teacher signing in wants the class they are about to take,
    # not a dashboard. Last in the list, so authentication has run.
    "app.middleware.TeacherLandingMiddleware",
]

ROOT_URLCONF = "lms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL in every real environment. JSONField needs MySQL 5.7+ (native JSON
# type) and CHECK constraints need 8.0.16+ — on anything older MySQL parses
# CHECK and ignores it, so the constraints in models.py would be decorative.
# MariaDB 10.2+ satisfies both.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("MYSQL_DB", "esquared_academy"),
        "USER": env("MYSQL_USER", "esquared"),
        "PASSWORD": env("MYSQL_PASSWORD", ""),
        "HOST": env("MYSQL_HOST", "127.0.0.1"),
        "PORT": env("MYSQL_PORT", "3306"),
        "CONN_MAX_AGE": int(env("MYSQL_CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": int(env("MYSQL_CONNECT_TIMEOUT", "10")),
            # STRICT_TRANS_TABLES turns silent truncation into an error.
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "TEST": {
            "CHARSET": "utf8mb4",
            "COLLATION": "utf8mb4_0900_ai_ci",
        },
    }
}

# Unit tests run against an in-memory database: created per run, held in
# RAM, discarded at the end. (Django has no H2 backend — H2 is a Java
# database — and SQLite's :memory: mode is the direct equivalent here.)
# Set DJANGO_TEST_ON_MYSQL=true to run the suite against MySQL instead,
# which is what CI should do before a release: SQLite is lenient about
# column types and ignores CHECK constraints Django cannot express.
if RUNNING_TESTS and not env_bool("DJANGO_TEST_ON_MYSQL"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
        "TEST": {"NAME": ":memory:"},
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("DJANGO_TIME_ZONE", "Asia/Karachi")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

# Uploaded files. One root, a flat folder per kind underneath it —
# text/ audio/ video/ picture/ other/ — plus _incoming/ for chunks of
# uploads still in progress. See app/files.py.
MEDIA_ROOT = Path(env("MEDIA_ROOT") or (BASE_DIR / "media"))

MEDIA_URL = env("MEDIA_URL") or "/media/"

# Large uploads arrive in chunks (see UploadSession), so no single request
# needs to be big. These bound what one request may hold: anything over
# 5 MB is streamed to a temporary file rather than buffered in memory.
FILE_UPLOAD_MAX_MEMORY_SIZE = int(env("FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(env("DATA_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024)))

# What the browser-side uploader slices files into. Bigger is faster on a
# good connection; smaller resumes more cheaply on a bad one.
UPLOAD_CHUNK_SIZE = int(env("UPLOAD_CHUNK_SIZE", str(5 * 1024 * 1024)))

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------
# REST framework
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "app.access.RolePermission",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Esquared Academy API",
    "DESCRIPTION": (
        "Assessment platform for Esquared Academy.\n\n"
        "Grades are classes. Question papers are versioned and immutable once "
        "locked; a locked version pins the prompt version each text question "
        "is marked by. Nothing is deleted \u2014 rows are voided, and purging "
        "is a separate, logged operation."
    ),
    "VERSION": "2.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api",
    "ENUM_NAME_OVERRIDES": {
        "TextFormatEnum": "app.models.TextFormat.choices",
        "QuestionTypeEnum": "app.models.QuestionType.choices",
        "ToleranceTypeEnum": "app.models.ToleranceType.choices",
        "SyllabusStatusEnum": "app.models.SyllabusStatus.choices",
        "PromptStatusEnum": "app.models.PromptStatus.choices",
        "PaperPurposeEnum": "app.models.PaperPurpose.choices",
        "PaperStatusEnum": "app.models.PaperStatus.choices",
        "CohortPurposeEnum": "app.models.CohortPurpose.choices",
        "MarkingMethodEnum": "app.models.MarkingMethod.choices",
        "AttemptStateEnum": "app.models.AttemptState.choices",
        "EvalMethodEnum": "app.models.EvalMethod.choices",
        "FileKindEnum": "app.files.FileKind.choices",
        "AttendanceStatusEnum": "app.models.AttendanceStatus.choices",
        "UploadStateEnum": "app.models.UploadState.choices",
    },
    "TAGS": [
        {"name": "academy-classes", "description": "Classes."},
        {"name": "students", "description": "Students and their enrolments."},
        {"name": "syllabi", "description": "A subject taught to a class in a year."},
        {"name": "questions", "description": "The reusable question bank."},
        {"name": "paper-versions", "description": "Frozen question cohorts."},
        {"name": "attempts", "description": "Sittings, answers and marking."},
    ],
}


# ---------------------------------------------------------------------
# Admin theme — Django JET Reboot
#
# The original django-jet was abandoned in 2018; this is the maintained
# fork (last release 1.3.10, September 2024), which is what supports
# Django 4 and 5. Verified against Django 5.2 here: the index, change
# lists, change forms, inlines and filters all render.
# ---------------------------------------------------------------------
# The skin everyone gets until they pick their own.
JET_DEFAULT_THEME = env("JET_THEME", "light-violet")

# Listing themes here puts a colour picker in the admin sidebar; each user's
# choice is stored against their account and overrides the default above.
# Set JET_SHOW_THEME_PICKER=false in .env to take the picker away and hold
# everyone to JET_THEME.
JET_THEMES = [
    {"theme": "default", "color": "#47bac1", "title": "Default"},
    {"theme": "green", "color": "#44b78b", "title": "Green"},
    {"theme": "light-green", "color": "#2faa60", "title": "Light green"},
    {"theme": "light-violet", "color": "#a464c4", "title": "Light violet"},
    {"theme": "light-blue", "color": "#5EADDE", "title": "Light blue"},
    {"theme": "light-gray", "color": "#222", "title": "Light gray"},
] if env_bool("JET_SHOW_THEME_PICKER", True) else []
# The admin home page. Jet's default lists every table the user has any
# permission on, plus links to Django's documentation and IRC channel —
# a developer's index, shown to teachers. app/dashboard.py replaces it
# with panels chosen for whoever is signed in.
JET_INDEX_DASHBOARD = "app.dashboard.AcademyDashboard"

# The page behind the "App" breadcrumb has its own dashboard. Left at the
# default it lists every model again, undoing the home page.
JET_APP_INDEX_DASHBOARD = "app.dashboard.AcademyAppIndexDashboard"

JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True

# The order the left menu is built in, grouped the way the ERD is:
# placement, curriculum, lessons, question bank, papers, marking, retention.
#
# Every entry carries an explicit `permissions` list, and that is not
# decoration. Jet builds this menu itself rather than from Django's own
# app list, and when an entry names a model the signed-in user may not
# see, it falls back to `has_perms = True` — so without these the menu
# advertises the whole system to every role. The permissions here are what
# make a Paper Setter's menu look like a Paper Setter's job.
#
# A group's permission is the one its other items imply: anyone who may
# work in that area holds it.
JET_SIDE_MENU_ITEMS = [
    {"label": "People & placement", "permissions": ["app.view_student"], "items": [
        {"name": "app.academyclass", "permissions": ["app.view_academyclass"]},
        {"name": "app.student", "permissions": ["app.view_student"]},
        {"name": "app.teacher", "permissions": ["app.view_teacher"]},
        {"name": "app.enrolment", "permissions": ["app.view_enrolment"]},
        {"name": "app.studentcohort", "permissions": ["app.view_studentcohort"]},
        {"name": "app.cohortmembership", "permissions": ["app.view_cohortmembership"]},
    ]},
    {"label": "Curriculum", "permissions": ["app.view_subject"], "items": [
        {"name": "app.subject", "permissions": ["app.view_subject"]},
        {"name": "app.syllabus", "permissions": ["app.view_syllabus"]},
        {"name": "app.studentsubject", "permissions": ["app.view_studentsubject"]},
        {"name": "app.teachingassignment", "permissions": ["app.view_teachingassignment"]},
    ]},
    {"label": "Timetable & lessons", "permissions": ["app.view_lesson"], "items": [
        {"label": "Home", "url": {"type": "reverse", "name": "teacher-home"},
         "permissions": ["app.view_lesson"]},
        {"label": "My day", "url": {"type": "reverse", "name": "my-day"},
         "permissions": ["app.view_lesson"]},
        {"label": "Calendar", "url": {"type": "reverse", "name": "calendar"},
         "permissions": ["app.view_lesson"]},
        {"label": "All lessons", "url": {"type": "reverse", "name": "browse"},
         "permissions": ["app.view_lesson"]},
        {"label": "My subjects", "url": {"type": "reverse", "name": "my-subjects"},
         "permissions": ["app.view_lesson"]},
        {"name": "app.timetableslot", "permissions": ["app.view_timetableslot"]},
        {"name": "app.lesson", "permissions": ["app.view_lesson"]},
        {"name": "app.lessontopic", "permissions": ["app.view_lessontopic"]},
    ]},
    # A student holds view_handout, so anything gated on it shows up in
    # their menu. The pages that are not theirs are gated on the change
    # permissions instead, which leaves a student with My work and
    # nothing else to be puzzled by.
    {"label": "Handouts & work", "permissions": ["app.view_handout"], "items": [
        {"label": "My work", "url": {"type": "reverse", "name": "my-work"},
         "permissions": ["app.view_handout"]},
        # Gated on view_handout so a student sees it. Posting is gated on
        # add_notice just below, which a student does not hold.
        {"label": "Notice board", "url": {"type": "reverse", "name": "notice-board"},
         "permissions": ["app.view_handout"]},
        {"label": "Post a notice", "url": {"type": "reverse", "name": "post-notice"},
         "permissions": ["app.add_notice"]},
        {"label": "Assignments", "url": {"type": "reverse", "name": "assignments"},
         "permissions": ["app.change_handout"]},
        {"label": "To approve", "url": {"type": "reverse", "name": "approvals"},
         "permissions": ["app.change_handout"]},
        {"label": "Checking", "url": {"type": "reverse", "name": "checking-browse"},
         "permissions": ["app.change_submission"]},
        {"label": "What's waiting", "url": {"type": "reverse", "name": "checking-queue"},
         "permissions": ["app.change_submission"]},
        {"name": "app.handout", "permissions": ["app.change_handout"]},
        {"name": "app.submission", "permissions": ["app.change_submission"]},
    ]},
    {"label": "Question bank", "permissions": ["app.view_question"], "items": [
        {"name": "app.question", "permissions": ["app.view_question"]},
        {"name": "app.questionattributetype", "permissions": ["app.view_questionattributetype"]},
        {"name": "app.questionattribute", "permissions": ["app.view_questionattribute"]},
        {"name": "app.evaluationprompt", "permissions": ["app.view_evaluationprompt"]},
        {"name": "app.promptversion", "permissions": ["app.view_promptversion"]},
    ]},
    {"label": "Papers", "permissions": ["app.view_questionpaper"], "items": [
        {"name": "app.questionpaper", "permissions": ["app.view_questionpaper"]},
        {"name": "app.paperversion", "permissions": ["app.view_paperversion"]},
        {"name": "app.paperitem", "permissions": ["app.view_paperitem"]},
        {"name": "app.paperassignment", "permissions": ["app.view_paperassignment"]},
    ]},
    {"label": "Attendance", "permissions": ["app.view_attendancesession"], "items": [
        {"name": "app.attendancesession", "permissions": ["app.view_attendancesession"]},
        {"name": "app.attendancerecord", "permissions": ["app.view_attendancerecord"]},
    ]},
    {"label": "Files", "permissions": ["app.view_attachment"], "items": [
        {"name": "app.attachment", "permissions": ["app.view_attachment"]},
        {"name": "app.attachmentlink", "permissions": ["app.view_attachmentlink"]},
        {"name": "app.uploadsession", "permissions": ["app.view_uploadsession"]},
    ]},
    {"label": "Marking", "permissions": ["app.view_evaluation"], "items": [
        {"name": "app.attempt", "permissions": ["app.view_attempt"]},
        {"name": "app.answer", "permissions": ["app.view_answer"]},
        {"name": "app.evaluation", "permissions": ["app.view_evaluation"]},
    ]},
    {"label": "Demo", "permissions": ["app.add_student"], "items": [
        {"label": "Demo data", "url": {"type": "reverse", "name": "demo"},
         "permissions": ["app.add_student"]},
    ]},
    {"label": "Administration", "permissions": ["auth.view_group"], "items": [
        {"name": "app.appuser", "permissions": ["app.view_appuser"]},
        {"name": "auth.group", "permissions": ["auth.view_group"]},
        {"name": "app.retentionpolicy", "permissions": ["app.view_retentionpolicy"]},
        {"name": "app.purgerun", "permissions": ["app.view_purgerun"]},
    ]},
]
