# Generated by Django 5.2.17 on 2026-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bootstrap_admin'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='answer_uix',
        ),
        migrations.RemoveConstraint(
            model_name='appuser',
            name='app_user_id_number_uix',
        ),
        migrations.RemoveConstraint(
            model_name='attempt',
            name='attempt_uix',
        ),
        migrations.RemoveConstraint(
            model_name='attempt',
            name='attempt_one_counted_uix',
        ),
        migrations.RemoveConstraint(
            model_name='cohortmembership',
            name='cohort_membership_uix',
        ),
        migrations.RemoveConstraint(
            model_name='enrolment',
            name='enrolment_one_grade_per_year_uix',
        ),
        migrations.RemoveConstraint(
            model_name='evaluationprompt',
            name='evaluation_prompt_name_uix',
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='grade_level_uix',
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='grade_short_name_uix',
        ),
        migrations.RemoveConstraint(
            model_name='paperitem',
            name='paper_item_slot_uix',
        ),
        migrations.RemoveConstraint(
            model_name='paperversion',
            name='paper_version_uix',
        ),
        migrations.RemoveConstraint(
            model_name='promptversion',
            name='prompt_version_uix',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='question_group_order_uix',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='student_admission_uix',
        ),
        migrations.RemoveConstraint(
            model_name='studentcohort',
            name='student_cohort_name_uix',
        ),
        migrations.RemoveConstraint(
            model_name='studentsubject',
            name='student_subject_uix',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='subject_short_name_uix',
        ),
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='syllabus_subject_grade_year_uix',
        ),
        migrations.RemoveConstraint(
            model_name='syllabustopic',
            name='syllabus_topic_uix',
        ),
        migrations.RemoveConstraint(
            model_name='syllabustopic',
            name='syllabus_topic_order_uix',
        ),
        migrations.RemoveConstraint(
            model_name='teacher',
            name='teacher_staff_no_uix',
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='teaching_assignment_uix',
        ),
        migrations.RemoveConstraint(
            model_name='topic',
            name='topic_short_name_uix',
        ),
        migrations.AddField(
            model_name='answer',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='counted_flag',
            field=models.BooleanField(default=True, editable=False, help_text="True on the one attempt that counts toward the record, NULL otherwise. Keeps 'one counted attempt per student per assignment' enforceable without a partial index.", null=True),
        ),
        migrations.AddField(
            model_name='binaryconfig',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='evaluationprompt',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='numericconfig',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='paperassignment',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='paperversion',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='retentionpolicy',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='studentcohort',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='active_flag',
            field=models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'paper_item', 'active_flag'), name='answer_uix'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(fields=('id_number', 'active_flag'), name='app_user_id_number_uix'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('paper_assignment', 'student', 'attempt_no', 'active_flag'), name='attempt_uix'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('paper_assignment', 'student', 'counted_flag'), name='attempt_one_counted_uix'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('student_cohort', 'enrolment', 'active_flag'), name='cohort_membership_uix'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'active_flag'), name='enrolment_one_grade_per_year_uix'),
        ),
        migrations.AddConstraint(
            model_name='evaluationprompt',
            constraint=models.UniqueConstraint(fields=('name', 'active_flag'), name='evaluation_prompt_name_uix'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('level', 'active_flag'), name='grade_level_uix'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('short_name', 'active_flag'), name='grade_short_name_uix'),
        ),
        migrations.AddConstraint(
            model_name='paperitem',
            constraint=models.UniqueConstraint(fields=('paper_version', 'slot', 'active_flag'), name='paper_item_slot_uix'),
        ),
        migrations.AddConstraint(
            model_name='paperversion',
            constraint=models.UniqueConstraint(fields=('question_paper', 'version_no', 'active_flag'), name='paper_version_uix'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('evaluation_prompt', 'version_no', 'active_flag'), name='prompt_version_uix'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('group', 'order_in_group', 'active_flag'), name='question_group_order_uix'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('admission_no', 'active_flag'), name='student_admission_uix'),
        ),
        migrations.AddConstraint(
            model_name='studentcohort',
            constraint=models.UniqueConstraint(fields=('grade', 'academic_year', 'name', 'active_flag'), name='student_cohort_name_uix'),
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(fields=('enrolment', 'syllabus', 'active_flag'), name='student_subject_uix'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('short_name', 'active_flag'), name='subject_short_name_uix'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('subject', 'grade', 'academic_year', 'active_flag'), name='syllabus_subject_grade_year_uix'),
        ),
        migrations.AddConstraint(
            model_name='syllabustopic',
            constraint=models.UniqueConstraint(fields=('syllabus', 'topic', 'active_flag'), name='syllabus_topic_uix'),
        ),
        migrations.AddConstraint(
            model_name='syllabustopic',
            constraint=models.UniqueConstraint(fields=('syllabus', 'sort_order', 'active_flag'), name='syllabus_topic_order_uix'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('staff_no', 'active_flag'), name='teacher_staff_no_uix'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'syllabus', 'role', 'active_flag'), name='teaching_assignment_uix'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'short_name', 'active_flag'), name='topic_short_name_uix'),
        ),
    ]
