# Generated by Django 5.2.17 on 2026-09-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_attendance_and_guardians'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='attendance_session_uix',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='syllabus_key',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='syllabus_id, or 0 for a whole-day register. The unique key uses this instead of syllabus, because NULLs are distinct in a unique index — two day registers for the same date would not collide.'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('grade', 'academic_year', 'date', 'period', 'syllabus_key', 'active_flag'), name='attendance_session_uix'),
        ),
    ]
