# Generated by Django 5.2.17 on 2026-09-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_attendance_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'base_manager_name': 'all_objects', 'ordering': ['subject', 'path', 'sort_order']},
        ),
        migrations.AddField(
            model_name='topic',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='0 for a top-level topic, 1 for its children.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The topic this one sits under. Empty for a top-level syllabus section.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='path',
            field=models.CharField(blank=True, default='', editable=False, help_text="Ancestor ids, root first, e.g. '4/17/23'. Descendants of a topic all start with that topic's path.", max_length=255),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent'], name='topic_parent__5e5648_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['path'], name='topic_path_39c41b_idx'),
        ),
    ]
