# Generated by Django 5.2.17 on 2026-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_populate_topic_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentlink',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='sort_order',
            field=models.IntegerField(verbose_name='sort'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='sort'),
        ),
    ]
