# Generated by Django 5.2.17 on 2026-09-03 16:34

import app.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sort_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Square picture — the width must equal the height — and under 100 KB.', max_length=256, null=True, upload_to=app.files.person_photo_path, validators=[app.files.validate_person_photo]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='Square picture — the width must equal the height — and under 100 KB.', max_length=256, null=True, upload_to=app.files.person_photo_path, validators=[app.files.validate_person_photo]),
        ),
    ]
