# Generated by Django 5.2.17 on 2026-09-03 16:54

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_student_photo_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='pass_mark_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="The mark a topic result must reach to count as passed. Stored here rather than on the result, so raising or lowering the bar re-reads the whole year's history without re-entering a mark.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='TopicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('score_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Out of 100. Empty means the topic has not been assessed yet.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessed_on', models.DateField(blank=True, null=True)),
                ('method', models.CharField(choices=[('rule', 'Rule'), ('ai', 'AI'), ('teacher', 'Teacher')], default='teacher', help_text='Who or what produced the mark: a teacher, a rule, or the AI marker.', max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_results', to='app.studentsubject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_results', to='app.topic')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topic_result',
                'ordering': ['topic__sort_order', 'topic__short_name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['topic', 'student_subject'], name='topic_resul_topic_i_c037c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_subject', 'topic', 'active_flag'), name='topic_result_uix')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
