# Generated by Django 5.2.17 on 2026-09-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_syllabus_pass_mark_pct_topicresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Residential address, as it should appear on an exam entry.'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="A guardian's address for a younger student, their own later. Not unique: siblings share one.", max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_contact_2',
            field=models.CharField(blank=True, default='', help_text='A second number for the guardian. Cambridge asks for two for candidates under 18.', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='Mobile number, with country code for an overseas number.', max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, default='', help_text='CNIC, B-Form or passport number, exactly as printed. Optional at admission; required before an exam entry.', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id_type',
            field=models.CharField(blank=True, choices=[('cnic', 'CNIC'), ('b_form', 'B-Form'), ('passport', 'Passport')], default='', help_text='Which document national_id came from.', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='As printed on the national ID. Many names do not split, so everything but the final word belongs here.', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Optional — leave empty when the ID carries a single name.', max_length=128),
        ),
    ]
