# Generated by Django 5.2.17 on 2026-09-04 23:24
#
# Hand-edited: 0015 added `email` and `national_id` with a default of "",
# so every existing student carried the same empty string. A unique index
# treats those as equal values and refuses them, while it treats NULLs as
# distinct. The blanks are therefore turned into NULL before the
# constraints are added.

from django.db import migrations, models


def blanks_to_null(apps, schema_editor):
    """Empty strings mean 'not known yet' — store that as NULL."""
    Student = apps.get_model("app", "Student")
    Student.objects.filter(email="").update(email=None)
    Student.objects.filter(national_id="").update(national_id=None)


def null_to_blanks(apps, schema_editor):
    """Reverse: NULL back to an empty string, so the migration can be undone."""
    Student = apps.get_model("app", "Student")
    Student.objects.filter(email__isnull=True).update(email="")
    Student.objects.filter(national_id__isnull=True).update(national_id="")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_address_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text='Unique to this student — two students may not share one. Optional at admission; required before an exam entry. Stored as empty (NULL) when not yet known.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, default=None, help_text='CNIC, B-Form or passport number, exactly as printed. Unique — no two students may share one. Optional at admission; required before an exam entry.', max_length=64, null=True),
        ),
        migrations.RunPython(blanks_to_null, null_to_blanks),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email', 'active_flag'), name='student_email_uix'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('national_id', 'active_flag'), name='student_national_id_uix'),
        ),
    ]
