# Generated by Django 5.2.17 on 2026-09-05 22:37

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_student_email_alter_student_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('period', models.CharField(help_text="Period label, matching the one used on registers — '1', '2', 'assembly'.", max_length=32)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(help_text='The subject, grade and year this slot teaches.', on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='app.syllabus')),
                ('teacher', models.ForeignKey(blank=True, help_text='Who normally teaches it. A lesson may name someone else.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='app.teacher')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable_slot',
                'ordering': ['day_of_week', 'period'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('period', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('plan', models.TextField(blank=True, default='', help_text='What will be taught, prepared in advance and reviewed by the head.')),
                ('plan_format', models.CharField(choices=[('plain', 'Plain'), ('html', 'HTML'), ('markdown', 'Markdown')], default='markdown', max_length=16)),
                ('log', models.TextField(blank=True, default='', help_text='Written after the lesson: what was actually covered, and anything the class needs.')),
                ('log_format', models.CharField(choices=[('plain', 'Plain'), ('html', 'HTML'), ('markdown', 'Markdown')], default='markdown', max_length=16)),
                ('date_taught', models.DateTimeField(blank=True, help_text='Set when the teacher logs the lesson. Empty means it was never written up — which is what the compliance view looks for.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('returned', 'Returned for changes'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='', help_text='Why it was returned. The point of review is improving the lesson, not only gating it.')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons_submitted', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='app.syllabus')),
                ('teacher', models.ForeignKey(blank=True, help_text='Who taught it, if not the usual teacher.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='app.teacher')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, help_text='The weekly slot this came from. Empty for a one-off lesson.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='app.timetableslot')),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ['-date', 'period'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('planned', models.BooleanField(default=True)),
                ('covered', models.BooleanField(default=False, help_text='Ticked when the lesson is logged after teaching.')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='app.lesson')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='app.topic')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_topic',
                'ordering': ['lesson', 'sort_order'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('lesson', 'topic', 'active_flag'), name='lesson_topic_uix')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['day_of_week', 'period'], name='timetable_s_day_of__f005f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('syllabus', 'day_of_week', 'period', 'active_flag'), name='timetable_slot_uix'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date'], name='lesson_date_67b927_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lesson_status_936ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date'], name='lesson_teacher_ca62eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('syllabus', 'date', 'period', 'active_flag'), name='lesson_uix'),
        ),
    ]
