# Generated by Django 5.2.17 on 2026-09-06 05:34

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_timetableslot_lesson_lessontopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('code', models.CharField(editable=False, help_text='Set on first save: subject, grade, year and a running number, e.g. ENG-E1-2026-H007. Printed on the sheet and quoted by every submission.', max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('instructions', models.TextField(blank=True, default='')),
                ('instructions_format', models.CharField(choices=[('plain', 'Plain'), ('html', 'HTML'), ('markdown', 'Markdown')], default='markdown', max_length=16)),
                ('is_assignment', models.BooleanField(default=True, help_text='Students hand work back from it. Clear it for a sheet that is only to read.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_rounds', models.PositiveSmallIntegerField(default=3, help_text='Submissions allowed, counting the first. Three means one attempt and two redoes; after that it goes to the teacher.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('date_activated', models.DateTimeField(blank=True, help_text='When it was handed out. Until then students cannot see it.', null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handouts_activated', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='app.syllabus')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handout',
                'ordering': ['-date_created'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HandoutLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='app.handout')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='app.lesson')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handout_lesson',
                'ordering': ['handout', 'sort_order'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('code', models.CharField(editable=False, help_text='Stamped with the moment it arrived. Identifies this hand-in and no other.', max_length=128)),
                ('round_no', models.PositiveSmallIntegerField(default=1, help_text="1 is the first hand-in; 2 and 3 are redoes of the questions marked wrong. 'Right first time' is worth keeping, so this is never overwritten.")),
                ('time_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('grading', 'Being marked'), ('marked', 'Marked'), ('returned', 'Returned for redoing'), ('accepted', 'Accepted'), ('rejected', 'Rejected — unreadable')], default='submitted', max_length=16)),
                ('awarded_marks', models.DecimalField(blank=True, decimal_places=2, help_text="This round's marks. The running total across rounds is worked out, not stored.", max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('date_marked', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(help_text='Whose work, and in which grade and year — so the record stays true after they move up.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='app.enrolment')),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='app.handout')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Empty while the grader holds it; set when a person confirms or overrides.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions_marked', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission',
                'ordering': ['-time_submitted'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='handout',
            index=models.Index(fields=['status'], name='handout_status_97134c_idx'),
        ),
        migrations.AddIndex(
            model_name='handout',
            index=models.Index(fields=['due_date'], name='handout_due_dat_3ba08a_idx'),
        ),
        migrations.AddConstraint(
            model_name='handout',
            constraint=models.UniqueConstraint(fields=('code', 'active_flag'), name='handout_code_uix'),
        ),
        migrations.AddConstraint(
            model_name='handoutlesson',
            constraint=models.UniqueConstraint(fields=('handout', 'lesson', 'active_flag'), name='handout_lesson_uix'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['state'], name='submission_state_e61481_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['handout', 'enrolment'], name='submission_handout_3c01d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('handout', 'enrolment', 'round_no', 'active_flag'), name='submission_round_uix'),
        ),
    ]
