# Generated by Django 5.2.17 on 2026-09-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_handout_handoutlesson_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='topic',
            field=models.ForeignKey(blank=True, help_text="The topic it belongs to, so it shows beside that topic on the teacher's day. Optional.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='app.topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teaching_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time actually spent teaching, in seconds.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='Set while the timer runs; cleared when paused or stopped.', null=True),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='carried',
            field=models.BooleanField(default=False, help_text='Put here automatically because the last lesson did not finish it. The teacher did not have to carry it forward.'),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Why it was left short, if it was. Never analysed — it is for the person reading it next week.', max_length=255),
        ),
    ]
