# Generated by Django 5.2.17 on 2026-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_handout_topic_lesson_teaching_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='timer_status',
            field=models.CharField(choices=[('idle', 'Not started'), ('running', 'Running'), ('paused', 'Paused'), ('ended', 'Ended')], default='idle', help_text='Recorded rather than guessed. Inferring it from the other fields made a pause after an ended class read as ended, so the teacher was offered Start instead of Resume.', max_length=8),
        ),
    ]
