# Generated by Django 5.2.17 on 2026-09-06 11:06

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_lesson_timer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=128)),
                ('chapter', models.CharField(blank=True, default='', max_length=128)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('subtopic', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecture_items', to='app.attachment')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_items', to='app.lesson')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecture_item',
                'ordering': ['lesson', 'sort_order', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
