# Generated by Django 5.2.17 on 2026-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_lectureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='handout',
            name='topic_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='topic (as written)'),
        ),
    ]
