# Generated by Django 5.2.17 on 2026-09-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_handout_chapter_handout_topic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureitem',
            name='subtopic',
        ),
    ]
