# Generated by Django 5.2.17 on 2026-09-06 11:48

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_lectureitem_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='cutoff_at',
            field=models.DateTimeField(blank=True, help_text='The hard close: nothing is accepted after this. Empty means late work is still taken, and marked late.', null=True),
        ),
        migrations.AddField(
            model_name='handout',
            name='open_from',
            field=models.DateTimeField(blank=True, help_text='Students see it from this moment. Empty means as soon as it is posted.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Handed in after the due moment. Late is recorded, not refused — the cut-off is what refuses.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='minutes_late',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handout',
            name='due_date',
            field=models.DateField(blank=True, help_text='When the work is expected.', null=True),
        ),
        migrations.CreateModel(
            name='HandoutExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('extended_to', models.DateTimeField(help_text='Their new deadline.')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handout_extensions', to='app.enrolment')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensions_granted', to=settings.AUTH_USER_MODEL)),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='app.handout')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handout_extension',
                'ordering': ['handout', 'enrolment'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('handout', 'enrolment', 'active_flag'), name='handout_extension_uix')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
