# Generated by Django 5.2.17 on 2026-09-06 12:07

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_handout_cutoff_at_handout_open_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sheet_version',
            field=models.PositiveIntegerField(default=0, help_text='Which version of the sheet this answered. 0 for work handed in before sheets were versioned.'),
        ),
        migrations.CreateModel(
            name='HandoutSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_changed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided', models.BooleanField(db_index=True, default=False)),
                ('active_flag', models.BooleanField(default=True, editable=False, help_text='True while the row is live, NULL once voided. Unique constraints include this column so that voided rows stop competing for the key: NULLs are distinct in a unique index on every backend, which is how soft deletion stays portable to MySQL, where partial indexes do not exist.', null=True)),
                ('date_voided', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.CharField(blank=True, default='', help_text='What changed, for whoever reads this later.', max_length=255)),
                ('replaced_on', models.DateTimeField(blank=True, help_text='When a later version took over. Empty on the current one.', null=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handout_sheets', to='app.attachment')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='app.handout')),
                ('voided_by', models.ForeignKey(blank=True, db_column='voided_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handout_sheet',
                'ordering': ['handout', '-version_no'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('handout', 'version_no', 'active_flag'), name='handout_sheet_uix')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
