# Generated by Django 5.2.17 on 2026-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_submission_sheet_version_handoutsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='allow_late',
            field=models.BooleanField(default=False, help_text='Keep taking work after the due date, marked late. Off means the due date is the close.'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='cutoff_at',
            field=models.DateTimeField(blank=True, help_text='Only used when late submissions are allowed. Empty then means late work is taken indefinitely.', null=True, verbose_name='late submissions until'),
        ),
    ]
