# Generated by Django 5.2.17 on 2026-09-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_handout_allow_late_alter_handout_cutoff_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_redo_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='redo_reason',
            field=models.CharField(blank=True, default='', help_text='What the student is being asked to put right.', max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='redo_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redos_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='The examiner who checked it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions_marked', to=settings.AUTH_USER_MODEL),
        ),
    ]
